<?php
$edt = array(
	2012=>array(
		9=>array(
			3=>array(
				array(
					"matter"=>1,
					"teacher"=>3,
					"group"=>"7 8 9",
					"room"=>114,
					"type"=>1,
					"hstart"=>"08",
					"mstart"=>"45",
					"hend"=>"10",
					"mend"=>"00"
				),
				array(
					"matter"=>1,
					"teacher"=>1,
					"group"=>"7",
					"room"=>234,
					"type"=>2,
					"hstart"=>"10",
					"mstart"=>"00",
					"hend"=>"12",
					"mend"=>"00"
				),
				array(
					"matter"=>1,
					"teacher"=>3,
					"group"=>"8",
					"room"=>235,
					"type"=>2,
					"hstart"=>"10",
					"mstart"=>"00",
					"hend"=>"12",
					"mend"=>"00"
				),
				array(
					"matter"=>1,
					"teacher"=>19,
					"group"=>"9",
					"room"=>222,
					"type"=>2,
					"hstart"=>"10",
					"mstart"=>"00",
					"hend"=>"12",
					"mend"=>"00"
				),
				array(
					"matter"=>1,
					"teacher"=>3,
					"group"=>"7 8",
					"room"=>201,
					"type"=>2,
					"hstart"=>"13",
					"mstart"=>"15",
					"hend"=>"15",
					"mend"=>"15"
				),
				array(
					"matter"=>1,
					"teacher"=>19,
					"group"=>"9",
					"room"=>305,
					"type"=>2,
					"hstart"=>"13",
					"mstart"=>"15",
					"hend"=>"15",
					"mend"=>"15"
				)
			)
		)
	)
);